name: Bug Report
description: Report a bug in the Yimporter application
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in Yimporter!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: When I upload a CSV file, the application crashes...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Upload file '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The file should have been processed successfully
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browsers have you seen the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Other
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Application crashes/data loss)
        - High (Major feature broken)
        - Medium (Feature partially working)
        - Low (Minor issue/cosmetic)
    validations:
      required: true